### ISSUE TITLE
database capacity?

### ISSUE THREAD

**Issue by anandagowdan3** [kripken/sql.js#106]
till how many tables can database created using sql.js store.? also how many records a table can hold?

**Comment by lovasoa** [comment]
All the [limits of sqlite](https://www.sqlite.org/limits.html) apply, since `sql.js` is nothing more than sqlite compiled in javascript.

But you won't be able to reach most of these limits with sql.js since it has its [own limits](https://github.com/kripken/sql.js/issues/20). If you want to work with large databases, I wouldn't recommend using sql.js, which stores the whole database in memory, but rather somethintg like [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API), a database that is directly implemented by the browser, and can store its data on the disk rather than in memory.

**Comment by ZoeCYC** [comment]
I currently have a csv file with around 150 million records. 

With this number, is it recommended to use sql.js?

And can IndexedDB take this number?

Cheers.

**Comment by lovasoa** [comment]
It obviously depends on the size of each record. But for large databases, I would definitely rather go for an InexedDB persistent database than for sql.js. And if the database is really huge (>1Gb), I would even try to find a way not to have to download all of it on the client side...

**Comment by ZoeCYC** [comment]
The size of each record is really small size; only ten columns and each column is either a short string (no more than 30 characters) or an integer (less than 1 million).

Is it worth a try of sql.js?

**Comment by lovasoa** [comment]
So your database is definitely over 1Gb. Many people don't even have 1Gb of free memory while browsing the web. All you are going to do is make their browsers become unresponsive. What can of database is this, and what kind of application are you trying to build? Is there no way to make your database stay on the server, and to make the client query the database when needed?

7 сентября 2015 г. 10:15:14 GMT+03:00, ZoeCYC <notifications@github.com> пишет:

**Comment by ZoeCYC** [comment]
Sorry I didn't make it clear.

My database is less than 8M. 

I did try to import the whole dataset into Firefox successfully though it take quite a while.

But the import failed when using Chrome.

**Comment by hi2u** [comment]
I'm curious to hear about this database of 150 million records that needs to run in a browser and has an average record size of less than 1 bit.

**Comment by dinedal** [comment]
Less than 1 bit? So smaller than a single bit? How do you represent that, with nulls?
