### ISSUE TITLE
Placeholder not working for table names

### ISSUE THREAD

**Issue by tiansivive** [kripken/sql.js#153]
Hi, 

I've been using sql.js for my latest project and everything seems to be working fine.I wanted to make a general GetByID query which would receive as params the table name and the id. However, it seems I can't use a placeholder for the table name as it the .prepare() method always throws out an exception error, more specifically a syntax error. I'm pretty sure my syntax is correct, it's a pretty simple query after all, so I'm wondering, does sql.js not support this kind of use case? shouldn't it?

My actual case is a fair bit more complex, but basically, the faulty code goes something like this:

```
 	//sql = 'SELECT * FROM :src WHERE id = :id;'
 	//args = {':src': 'suppliers', ':id': 1}
 	var stmt = db.main.prepare(sql); //this throws syntax error
	if(args && !_.isEmpty(args)) stmt.bind(args);
	while(stmt.step()){
		rows.push(stmt.getAsObject());
	}
	stmt.free();
```

**Comment by lovasoa** [comment]
No, you can't. This is indeed a syntax error. sql.js is just a wrapper to SQLite, that doesn't allow that (nor does MySQL, PostgreeSQL, or any database engine I know). The thing is that in order to prepare your query, the database has to know what tables will be queried. That allows it to prepare an execution plan just once, that will be used every time the prepared query will be executed.

**Comment by lovasoa** [comment]
You should read this Wikipedia article on prepared statements in order to understand how they work: https://en.m.wikipedia.org/wiki/Prepared_statement
