### ISSUE TITLE
get an object array

### ISSUE THREAD

**Issue by EmileSonneveld** [kripken/sql.js#184]
With `db.prepare("SELECT ...")`, I get a handy JavaScript object, but only one value.
With `db.exec("SELECT ...")`, I get multiple values, but in a not handy structure.

I would like to get a result where this is possible: `results[0].last_name`. Maybe there is a function that already returns such result?
For now, I'll write a piece of JavaScript code that will convert the structure, based on the `db.exec` result.

An out of the box solution would be awesome!

**Comment by lovasoa** [comment]
Getting all the results as an array is just one line of js.

```js
for(var result = []; stmt.step();) result.push(stmt.getAsObject());
```

But it's often preferable to fetch the results as they are needed. That's why sqlite3's C api doesn't offer the ability to fetch the results as an array, nor sql.js, which is a simple port to js of sqlite3, with a few helper functions.

**Comment by CodeLiftSleep** [comment]
Is there a method to return these as JSON objects instead of a column array and then a row array with the column value array?

So for instance I run db.exec() and get columns [52], values[32] and then each of the 32 values has an array of 52 columns matching the column value to the row value. What I want is a JSON array of objects like:
[{ id: 1, Name: "Mike", Position: "Programmer"}, {id: 2, Name: "Joe", Position: "Tester"}, {id: 3, Name: "Mary", Position: "Manager"}] 

Is is possible to do that with the getAsObject() method and if so, how would I go about that>  If you could write show from start to finish it would be great, as I feel like I am flying blind with some of this...and if ther isn't a way, I really think you should write a method to do this as this is the way most peopel would be using the data inside Javacscript as the majority of other libraries are looking for data in this format...

For example, I want to take this data and display it in UI-Grid, but it is much easier to do so as a JSON object than trying to figure out how to configure the arrays properly...

**Comment by EmileSonneveld** [comment]
Work like a charm, thank you. This is going way more smooth than indexedDb :)

**Comment by tracker1** [comment]
It might be nice to expose result as an es6 enumerable...  At least then in modern browsers, it can be used like an array, while under the covers getting each one, one at a time.

http://www.2ality.com/2015/10/enumerability-es6.html
