### ISSUE TITLE
Build without greedy uncaughtException handler

### ISSUE THREAD

**Issue by danielbarela** [kripken/sql.js#262]
This is related to #173.

I wrote up what is happening here: https://github.com/danielbarela/sqljs-uncaughtexception

This issue in emscripten indicates that the library can be built without the greedy exception handler:
https://github.com/emscripten-core/emscripten/issues/5957

Can this option be added to the sql.js build and republished?

**Comment by Taytay** [comment]
Oh wow! I just read about this behavior and came across this Emscripten issue: https://github.com/emscripten-core/emscripten/issues/2629

That's where the code originally got added. I've been reading about this, and my current thought is that if we were compiling an executable, it would be appropriate to have this global exception handling added so that Emscripten can manage exiting from the process, as it apparently wants to do. However, for a library like Sql.js, it feels inappropriate to me to handle global exceptions simply by including the library in your Node app. So, I agree and will fix this in #255. We'll see what the maintainers think.

**Comment by lovasoa** [comment]
I agree we should not handle global exceptions
