### ISSUE TITLE
WebWorker and pass sqlite file

### ISSUE THREAD

**Issue by stedidg** [kripken/sql.js#286]
In your example it is possible to open a sqlite database using the html 'input' button.
Is it possible to use the same web worker by directly passing the sqlite database address (eg: 'dbsqlite.sqlite'), present on the server?
Thanks

**Comment by lovasoa** [comment]
Hello, and thank you for your interest in sql.js. There is an [example](https://github.com/kripken/sql.js#loading-a-database-from-a-server) in the readme explaining how to do what you want.

I am going to close this because this is a question, and not an issue with sql.js. A better place to ask programming questions is stackoverflow.
