### ISSUE TITLE
Build with SQLite 3.31

### ISSUE THREAD

**Issue by AnyhowStep** [kripken/sql.js#338]
https://www.sqlite.org/releaselog/3_31_1.html

The most compelling reason for this is,
> Add support for generated columns.

https://www.sqlite.org/gencol.html

-----

Generated columns are finally in SQLite

**Comment by brodybits** [comment]
I just raised PR #339 to do this update.

FYI I generally do my own custom builds since I need some custom features and some other features to be enabled. Here are a couple of my custom build branches for your reference (with `dist` artifacts *not* committed):

- https://github.com/brodybits/sql.js/tree/brodybits-custom-build
- https://github.com/brodybits/sql.js/tree/eu-ext-custom-build

**Comment by brodybits** [comment]
SQLite 3.31.1 update should be available in master now.
